name: Deploy demo-blog

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Detect changes
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            frontend:
              - 'client/**'
              - 'demo-blog/client/**'
            backend:
              - 'server/**'
              - 'demo-blog/server/**'
              - 'docker-compose.yml'

      - name: Build frontend
        if: steps.changes.outputs.frontend == 'true'
        run: |
          cd client
          npm i --force
          npm run build

      - name: Deploy frontend
        if: steps.changes.outputs.frontend == 'true'
        run: |
          sudo rm -rf /var/www/demo-blog/client
          sudo mkdir -p /var/www/demo-blog/client
          sudo cp -r client/dist/* /var/www/demo-blog/client
          sudo find /var/www/demo-blog/client -type d -exec chmod 755 {} \;
          sudo find /var/www/demo-blog/client -type f -exec chmod 644 {} \;

      - name: Deploy backend
        if: steps.changes.outputs.backend == 'true'
        run: |
          if [ -d "server" ]; then
            sudo rm -rf ~/app/server
            sudo mkdir -p ~/app/server
            sudo cp -r server/* ~/app/server
          else
            echo "Папка server не найдена"
          fi

      - name: Deploy docker-compose
        if: steps.changes.outputs.backend == 'true'
        run: |
          sudo cp docker-compose.yml ~/app/docker-compose.yml

      - name: Restart containers
        if: steps.changes.outputs.backend == 'true'
        run: |
          cd ~/app
          sudo docker compose -f docker-compose.yml down --remove-orphans || true
          sudo docker compose -f docker-compose.yml build --no-cache
          sudo docker compose -f docker-compose.yml up -d --force-recreate

      - name: Delete server source files
        if: steps.changes.outputs.backend == 'true'
        run: |
          sudo rm -rf ~/app/server/*
